language: cpp
compiler:
  - gcc
  - clang
env:
  - HAVE_CIMG=0
  - HAVE_CIMG=1

# The CImg.h on ubuntu precise 12.04 is too old to compile with clang
matrix:
  include:
    - compiler: gcc
      env: HAVE_CIMG=1
    - compiler: clang
      env: HAVE_CIMG=0
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
install:
  - sudo apt-get install cimg-dev
script:
  - make -j2 BITS=64 HAVE_CIMG=$HAVE_CIMG CIMG_INCLUDE=/usr/include
