os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
  fast_finish: true

# Travis CI has 1.5 cores per VM, take advantage of it
# But first, the makefiles have to be fixed: all plugins are using the same .o's
#env:
#  - MAKEFLAGS="-j 2"

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update

# CImg is now downloaded by CImg/Makefile, no need to install it
#install:
#  - sudo apt-get install cimg-dev

script:
  - make CONFIG=debug
  - make nomulti CONFIG=debug


